name: turtle_house
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2022.10.11=hecd8cb5_0
  - libffi=3.4.2=hecd8cb5_6
  - ncurses=6.3=hca72f7f_3
  - openssl=1.1.1s=hca72f7f_0
  - python=3.10.9=h218abb5_0
  - readline=8.2=hca72f7f_0
  - sqlite=3.40.1=h880c91c_0
  - tk=8.6.12=h5d9f67b_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h6c40b1e_1
  - zlib=1.2.13=h4dc903c_0
  - pip:
    - certifi==2022.12.7
    - contourpy==1.0.7
    - cycler==0.11.0
    - fonttools==4.38.0
    - ghostscript==0.7
    - kiwisolver==1.4.4
    - matplotlib==3.6.3
    - numpy==1.24.1
    - packaging==23.0
    - pillow==9.4.0
    - pip==22.3.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pythonturtle==0.3.2
    - setuptools==65.6.3
    - six==1.16.0
prefix: /Users/marshuang/anaconda3/envs/turtle_house

